---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: nalms
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 5Gi
    deleteClaim: false
  resources:
    requests:
      memory: 3Gi
      cpu: "2"
    limits:
      memory: 6Gi
      cpu: "4"

